apiVersion: v1
kind: Service
metadata:
  name: happy-cms
  labels:
    monokle.io/demo: kustomize-happy-cms
spec:
  selector:
    app: happy-cms
  ports:
    - name: http-web
      protocol: TCP
      port: 80
      targetPort: 8081
